// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectLocal provides a mock function for the type MockClient
func (_mock *MockClient) ConnectLocal(host string, port string, user string, password string) error {
	ret := _mock.Called(host, port, user, password)

	if len(ret) == 0 {
		panic("no return value specified for ConnectLocal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = returnFunc(host, port, user, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ConnectLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectLocal'
type MockClient_ConnectLocal_Call struct {
	*mock.Call
}

// ConnectLocal is a helper method to define mock.On call
//   - host string
//   - port string
//   - user string
//   - password string
func (_e *MockClient_Expecter) ConnectLocal(host interface{}, port interface{}, user interface{}, password interface{}) *MockClient_ConnectLocal_Call {
	return &MockClient_ConnectLocal_Call{Call: _e.mock.On("ConnectLocal", host, port, user, password)}
}

func (_c *MockClient_ConnectLocal_Call) Run(run func(host string, port string, user string, password string)) *MockClient_ConnectLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_ConnectLocal_Call) Return(err error) *MockClient_ConnectLocal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ConnectLocal_Call) RunAndReturn(run func(host string, port string, user string, password string) error) *MockClient_ConnectLocal_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockClient
func (_mock *MockClient) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockClient_Expecter) Ping() *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockClient_Ping_Call) Run(run func()) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(err error) *MockClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func() error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
