.PHONY: modd
modd:
	go mod download

.PHONY: build
build:
	go build ./...

.PHONY: build-mac-silicon
build-mac-silicon:
	go build -tags dynamic ./...

.PHONY: swag
swag:
	swag init -g cmd/main.go --parseDependency --parseInternal
	cp ./docs/swagger.json ./docs/go-health-checker-openapi.json
	cp ./docs/swagger.yaml ./docs/go-health-checker-openapi.yaml

	@if [ -f "./docs/docs.go" ]; then \
		fl="$$(head -n1 ./docs/docs.go | tr -d '\r\n')"; \
		if printf "%s" "$$fl" | grep -q "swaggo/swag"; then \
			{ printf "// Code generated by swaggo/swag; DO NOT EDIT.\n\n"; tail -n +2 ./docs/docs.go; } > ./docs/docs.go.tmp && mv ./docs/docs.go.tmp ./docs/docs.go; \
		fi; \
	fi

	@if [ -f "./docs/docs.go" ]; then \
		lc="$$(tail -c1 ./docs/docs.go | od -An -t x1 | tr -d ' ')"; \
		if [ "$$lc" != "0a" ]; then \
			printf "\n" >> ./docs/docs.go; \
		fi; \
	fi

.PHONY: go-test
# Define here all the route patterns you want to test
PKG_PATHS := ./domain/... ./pkg/...

# 1) We list all packages from those sources
# 2) We filter those that DO NOT contain “/mocks/”
# 3) We run the tests with coverage
# 4) Show the report
go-test:
	@ALL_PKGS=$$(go list $(PKG_PATHS)) && \
	PKGS=$$(echo "$$ALL_PKGS" | tr ' ' '\n' | grep -v '/mocks/' | grep -v '/mapper' | grep -v '/proto' | grep -v '/models') && \
	go test -coverprofile=coverage.out -v $$PKGS && \
	go tool cover -func=coverage.out

go-test-report:
	go tool cover -html=coverage.out

.PHONY: mockery
mockery:
	mockery --config .mockery.yml

.PHONY: lint
lint:
	golangci-lint -v run

.PHONY: code-format
code-format:
	goimports -l -w .
	gofmt -l -w .
	gofumpt -l -w .

validate:
	make code-format
	make lint
	make go-test

install-swag:
	go install -v github.com/swaggo/swag/cmd/swag@latest

mockery-install:
	go install -v github.com/vektra/mockery/v3@v3.2.5

install-lint-binaries:
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

	golangci-lint --version

install-lint-windows-chocolatey:
	choco install golangci-lint

install-lint-windows-scoop:
	choco install golangci-lint

install-lint-mac-silicon:
	brew install golangci-lint
	brew upgrade golangci-lint

install-lint-dependencies:
	go install -v github.com/kisielk/errcheck@latest
	go install -v github.com/polyfloyd/go-errorlint@latest
	go install -v golang.org/x/tools/cmd/goimports@latest
	go install -v github.com/bombsimon/wsl/v3/cmd/...@latest
	go install -v honnef.co/go/tools/cmd/staticcheck@latest
	go install -v github.com/mgechev/revive@latest
	go install -v github.com/gordonklaus/ineffassign@latest
	go install -v golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@master
	go install -v golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
	go install -v golang.org/x/tools/go/analysis/passes/unmarshal/cmd/unmarshal@latest
	go install -v github.com/dcu/closecheck@latest
	go install -v github.com/alexkohler/nakedret/v2/cmd/nakedret@latest
	go install -v mvdan.cc/gofumpt@latest