// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIClient creates a new instance of MockIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIClient {
	mock := &MockIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIClient is an autogenerated mock type for the IClient type
type MockIClient struct {
	mock.Mock
}

type MockIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIClient) EXPECT() *MockIClient_Expecter {
	return &MockIClient_Expecter{mock: &_m.Mock}
}

// Disconnect provides a mock function for the type MockIClient
func (_mock *MockIClient) Disconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockIClient_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx
func (_e *MockIClient_Expecter) Disconnect(ctx interface{}) *MockIClient_Disconnect_Call {
	return &MockIClient_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *MockIClient_Disconnect_Call) Run(run func(ctx context.Context)) *MockIClient_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIClient_Disconnect_Call) Return(err error) *MockIClient_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_Disconnect_Call) RunAndReturn(run func(ctx context.Context) error) *MockIClient_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockIClient
func (_mock *MockIClient) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockIClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockIClient_Expecter) Ping() *MockIClient_Ping_Call {
	return &MockIClient_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockIClient_Ping_Call) Run(run func()) *MockIClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIClient_Ping_Call) Return(err error) *MockIClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIClient_Ping_Call) RunAndReturn(run func() error) *MockIClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
