// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"context"

	"github.com/samuskitchen/go-health-checker/beer/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBeerRepository creates a new instance of MockBeerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerRepository {
	mock := &MockBeerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBeerRepository is an autogenerated mock type for the BeerRepository type
type MockBeerRepository struct {
	mock.Mock
}

type MockBeerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeerRepository) EXPECT() *MockBeerRepository_Expecter {
	return &MockBeerRepository_Expecter{mock: &_m.Mock}
}

// GetAllBeers provides a mock function for the type MockBeerRepository
func (_mock *MockBeerRepository) GetAllBeers(ctx context.Context) ([]model.Beers, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeers")
	}

	var r0 []model.Beers
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.Beers, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.Beers); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Beers)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerRepository_GetAllBeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBeers'
type MockBeerRepository_GetAllBeers_Call struct {
	*mock.Call
}

// GetAllBeers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBeerRepository_Expecter) GetAllBeers(ctx interface{}) *MockBeerRepository_GetAllBeers_Call {
	return &MockBeerRepository_GetAllBeers_Call{Call: _e.mock.On("GetAllBeers", ctx)}
}

func (_c *MockBeerRepository_GetAllBeers_Call) Run(run func(ctx context.Context)) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBeerRepository_GetAllBeers_Call) Return(beerss []model.Beers, err error) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Return(beerss, err)
	return _c
}

func (_c *MockBeerRepository_GetAllBeers_Call) RunAndReturn(run func(ctx context.Context) ([]model.Beers, error)) *MockBeerRepository_GetAllBeers_Call {
	_c.Call.Return(run)
	return _c
}
