// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"context"

	"github.com/samuskitchen/go-health-checker/beer/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBeerService creates a new instance of MockBeerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerService {
	mock := &MockBeerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBeerService is an autogenerated mock type for the BeerService type
type MockBeerService struct {
	mock.Mock
}

type MockBeerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeerService) EXPECT() *MockBeerService_Expecter {
	return &MockBeerService_Expecter{mock: &_m.Mock}
}

// GetAllBeers provides a mock function for the type MockBeerService
func (_mock *MockBeerService) GetAllBeers(ctx context.Context) ([]model.BeersResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeers")
	}

	var r0 []model.BeersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.BeersResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.BeersResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BeersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBeerService_GetAllBeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBeers'
type MockBeerService_GetAllBeers_Call struct {
	*mock.Call
}

// GetAllBeers is a helper method to define mock.On call
//   - ctx
func (_e *MockBeerService_Expecter) GetAllBeers(ctx interface{}) *MockBeerService_GetAllBeers_Call {
	return &MockBeerService_GetAllBeers_Call{Call: _e.mock.On("GetAllBeers", ctx)}
}

func (_c *MockBeerService_GetAllBeers_Call) Run(run func(ctx context.Context)) *MockBeerService_GetAllBeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBeerService_GetAllBeers_Call) Return(beersResponses []model.BeersResponse, err error) *MockBeerService_GetAllBeers_Call {
	_c.Call.Return(beersResponses, err)
	return _c
}

func (_c *MockBeerService_GetAllBeers_Call) RunAndReturn(run func(ctx context.Context) ([]model.BeersResponse, error)) *MockBeerService_GetAllBeers_Call {
	_c.Call.Return(run)
	return _c
}
