// Code generated by swaggo/swag; DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/beers": {
            "get": {
                "description": "Get all beers",
                "tags": [
                    "Beer"
                ],
                "operationId": "GetAllBeersHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_samuskitchen_go-health-checker_beer_model.BeersResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/beer_handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "beer_handler.errorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_samuskitchen_go-health-checker_beer_model.BeersResponse": {
            "type": "object",
            "properties": {
                "brewery": {
                    "description": "Producer brewery",
                    "type": "string"
                },
                "country": {
                    "description": "Country of origin",
                    "type": "string"
                },
                "created_at": {
                    "description": "Creation date",
                    "type": "string"
                },
                "currency": {
                    "description": "Currency code",
                    "type": "string"
                },
                "id": {
                    "description": "Unique beer identifier",
                    "type": "integer"
                },
                "name": {
                    "description": "Beer name",
                    "type": "string"
                },
                "price": {
                    "description": "Unit price",
                    "type": "number"
                },
                "updated_at": {
                    "description": "Last update date",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api-health-checker",
	Schemes:          []string{},
	Title:            "Swagger Data the Health Checker",
	Description:      "This is health checker API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
