// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package _mocks

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBeerHandler creates a new instance of MockBeerHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBeerHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBeerHandler {
	mock := &MockBeerHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBeerHandler is an autogenerated mock type for the BeerHandler type
type MockBeerHandler struct {
	mock.Mock
}

type MockBeerHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBeerHandler) EXPECT() *MockBeerHandler_Expecter {
	return &MockBeerHandler_Expecter{mock: &_m.Mock}
}

// GetAllBeersHandler provides a mock function for the type MockBeerHandler
func (_mock *MockBeerHandler) GetAllBeersHandler(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBeersHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBeerHandler_GetAllBeersHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBeersHandler'
type MockBeerHandler_GetAllBeersHandler_Call struct {
	*mock.Call
}

// GetAllBeersHandler is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockBeerHandler_Expecter) GetAllBeersHandler(c interface{}) *MockBeerHandler_GetAllBeersHandler_Call {
	return &MockBeerHandler_GetAllBeersHandler_Call{Call: _e.mock.On("GetAllBeersHandler", c)}
}

func (_c *MockBeerHandler_GetAllBeersHandler_Call) Run(run func(c echo.Context)) *MockBeerHandler_GetAllBeersHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBeerHandler_GetAllBeersHandler_Call) Return(err error) *MockBeerHandler_GetAllBeersHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBeerHandler_GetAllBeersHandler_Call) RunAndReturn(run func(c echo.Context) error) *MockBeerHandler_GetAllBeersHandler_Call {
	_c.Call.Return(run)
	return _c
}
